#!/usr/bin/env python3

# pylint: disable=invalid-name, wrong-import-position

''' Wrapper for the lirc_setup thing, meant to be a symlink. '''

import sys
import os.path

_HERE = os.path.dirname(os.path.realpath(__file__))
sys.path.insert(0, _HERE)

if os.path.exists(os.path.join(_HERE, '..','..', 'lirc.pc.in')):
    sys.path.insert(0, os.path.join(_HERE, '..','..', 'python-pkg'))

import mvc_control
mvc_control.main()
