dist: bionic
language: c
before_install:
- sudo apt-get -qqy update && sudo apt-get install libdvbcsa-dev dvb-apps libssl-dev
  -qqy
- echo -n | openssl s_client -connect https://scan.coverity.com:443 | sed -ne '/-BEGIN
  CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
script:
- "./configure"
- make -j 4
- make test
env:
  global:
          secure: "13s/vbrHJAkRCQAxScLJ+atOQTXCHNfjV40FXlNWSReTSSJPhebw4tMSRdqp7YPnydMiXitQbO1C3mjJ4U6KJz3e9PpvvaZaY1CGGccp0+iRApVoL1+KTg8KQg7c6ubWk/Nyx4l2eA1Dmie6gZdD1F1juCH0UjHbJRAoq8WIgZvy1aiwXaAbh4XkZlZ1t/k8IHRWbyxaxRIazlwYRFjHoFCAHyxkUOSQJj5j1dBNAgNweEDZ0rVKLnx1VRa0u0y+p17PivP+b9hcSLX1JcjTO/yZzfTRVSjRQQzCoeJ8DErZoHUr9eF8P210TVUYU9nE3my7Vr1WserNq14GYlNXlWkofntaql56Ru1+b835WtrvxRQKtkFgX0w2+9unrwYbhTpPMdJjGMZjkkepkW5kUoIo/NP1ZTJSgd7BPOuSXqJBZVSgJXK5eoTTn1xLUiqGyQLLBj4/nvajUu0oq/uFuk2wMbDtrHSSvU0jxJmYxL+2X8GxU2PuEP+LvaoXgFJxqpJSDWuuUBYu1B24vq3OqWtB8FqUYQXJsj1lk//klKmVnr/R6yyUylo8rC4VnwfNcR98rccg2O6E1RnqzVVcAwUi+7TU1UGdn3F43RmxJaqPRp0/BnKSDGQU1+ygaFN3INpQQ8ZLRfxEa8Tjyng08SZMzpvARVdndGlN4zKRFAo="
addons:
  coverity_scan:
    project:
      name: catalinii/minisatip
      description: minisatip
    notification_email: t_cata_2000@yahoo.com
    build_command_prepend: "./configure"
    build_command: make
    branch_pattern: master
