language: c

os:
  - linux
  - osx

compiler:
  - gcc
  - clang

before_install:
- 'if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export CFLAGS="-I/usr/local/opt/openssl/include $CFLAGS" LDFLAGS="-L/usr/local/opt/openssl/lib $LDFLAGS"; fi'

# before build script, run autoreconf
before_script: autoreconf -fiv