.core-defs:
  variables:
    JNI_PATH: .
    CORENAME: mednafen_psx

.core-defs-hw:
  extends: .core-defs
  variables:
    CORENAME: mednafen_psx_hw
    HAVE_HW: 1

.core-defs-hw-lightrec:
  extends: .core-defs
  variables:
    CORENAME: mednafen_psx_hw
    HAVE_HW: 1
    HAVE_LIGHTREC: 1

include:
  - template: Jobs/Code-Quality.gitlab-ci.yml
  - project: 'libretro-infrastructure/ci-templates'
    file: '/linux-x64.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/windows-x64-mingw.yml'
  - project: 'libretro-infrastructure/ci-templates'
    file: '/android-jni.yml'

stages:
  - build-prepare
  - build-shared
  - build-static
  - test

#Desktop
libretro-build-linux-x64:
  extends:
    - .core-defs-hw-lightrec
    - .libretro-linux-x64-make-default

libretro-build-windows-x64:
  extends:
    - .core-defs-hw-lightrec
    - .libretro-windows-x64-mingw-make-default
    
# Android
android-armeabi-v7a:
  extends:
    - .core-defs-hw
    - .libretro-android-jni-armeabi-v7a

android-arm64-v8a:
  extends:
    - .core-defs-hw
    - .libretro-android-jni-arm64-v8a

android-x86_64:
  extends:
    - .core-defs-hw
    - .libretro-android-jni-x86_64
    
android-x86:
  extends:
    - .core-defs-hw
    - .libretro-android-jni-x86
