name: mediainfo-gui
version: 18.05
summary: Graphical utility for reading information from audio/video files
description: |
  MediaInfo is a utility used for retrieving technical information and other
  metadata about audio or video files.
confinement: strict
grade: stable

apps:
  mediainfo-gui:
    command: desktop-launch mediainfo-gui
    plugs:
      - unity7
      - home
      - network

parts:
  mediainfo-gui:
    plugin: autotools-subdir
    source: MediaInfo
    make-directory: Project/GNU/GUI
    build-packages:
      - libwxgtk3.0-dev
      - zlib1g-dev
      - libcurl4-gnutls-dev
    after:
      - desktop-gtk3
      - libmediainfo
      - libzen
      - build-essential

  libmediainfo:
    plugin: autotools-subdir
    source: MediaInfoLib
    make-directory: Project/GNU/Library
    configflags:
      - --enable-shared
      - --disable-static
      - --with-libcurl
      - --with-libmms
    build-packages:
      - libcurl4-gnutls-dev
      - libglib2.0-dev
      - libmms-dev
      - zlib1g-dev
    after:
      - libzen
      - build-essential
    snap:
      - lib/libmediainfo.*

  libzen:
    plugin: autotools-subdir
    source: ZenLib
    make-directory: Project/GNU/Library
    configflags:
      - --enable-shared
      - --disable-static
    snap:
      - lib/libzen.*
    after:
      - build-essential

  build-essential:
    plugin: nil
    build-packages:
      - build-essential
