'\" t
.\"     Title: megaget
.\"    Author: [see the "AUTHOR" section]
.\" Generator: DocBook XSL Stylesheets vsnapshot <http://docbook.sf.net/>
.\"      Date: 04/15/2020
.\"    Manual: Megatools Manual
.\"    Source: megatools 1.10.2
.\"  Language: English
.\"
.TH "MEGAGET" "1" "04/15/2020" "megatools 1.10.2" "Megatools Manual"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
megaget \- download files from your Mega\&.nz account
.SH "SYNOPSIS"
.sp
.nf
\fImegaget\fR [\-\-no\-progress] [\-\-path <path>] <remotepaths>\&...
\fImegaget\fR \-\-path \- <remotefile>
.fi
.SH "DESCRIPTION"
.sp
Downloads files from your Mega\&.nz account\&.
.sp
\fBNOTE\fR: If you want to download entire directories, use \fBmegacopy\fR(1)\&.
.SH "OPTIONS"
.PP
\-\-path <path>
.RS 4
Local path to download to\&. If this path is a directory, files are placed into the directory\&. If this path doesn\(cqt exist, and it\(cqs parent directory does, the file will be downloaded to a specified file (this only works if you specify exactly one remote path)\&.
.sp
If
<path>
is
\-, remote file will be streamed to stdout\&.
.RE
.PP
\-\-no\-progress
.RS 4
Disable download progress reporting\&. This is implied when streaming\&.
.RE
.PP
\-\-disable\-resume
.RS 4
Don\(cqt resume downloads from partially dowloaded file\&. Default is to resume\&.
.RE
.PP
\-u <email>, \-\-username <email>
.RS 4
Account username (email)
.RE
.PP
\-p <password>, \-\-password <password>
.RS 4
Account password
.RE
.PP
\-\-no\-ask\-password
.RS 4
Never ask interactively for a password
.RE
.PP
\-\-reload
.RS 4
Reload filesystem cache
.RE
.PP
\-\-limit\-speed <speed>
.RS 4
Set maximum allowed upload and download speed in KiB/s\&. This option overrides config file settings\&. 0 means no limit\&. When using ParallelTransfers > 1, upload speed limit is applied to each transfer individually\&.
.RE
.PP
\-\-proxy <proxy>
.RS 4
Use proxy server to connect to mega\&.nz\&. This option overrides config file settings\&. More information can be found in libcurl documentation at
https://curl\&.haxx\&.se/libcurl/c/CURLOPT_PROXY\&.html\&. Some acceptable values are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
none
: Disable proxy if it was enabled in the config file\&.
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
socks5://localhost:9050
: Local SOCKSv5 proxy server
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
socks5h://localhost:9050
: Local SOCKSv5 proxy server with DNS handled by the proxy
.RE
.RE
.PP
\-\-config <path>
.RS 4
Load configuration from a file
.RE
.PP
\-\-ignore\-config\-file
.RS 4
Disable loading \&.megarc
.RE
.PP
\-\-debug [<options>]
.RS 4
Enable debugging of various aspects of the megatools operation\&. You may enable multiple debugging options separated by commas\&. (eg\&.
\-\-debug api,fs)
.sp
Available options are:
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
http: Dump HTTP request/response details (can be used to debug connection/proxy issues)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
api: Dump Mega\&.nz API calls
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
fs: Dump Mega\&.nz filesystem (may require
\-\-reload
to actually print something)
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
cache: Dump cache contents
.RE
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
tman: Dump transfer manager events
.RE
.RE
.PP
\-\-version
.RS 4
Show version information
.RE
.PP
<remotepaths>
.RS 4
One or more remote files to download\&.
.RE
.PP
<remotefile>
.RS 4
Remote path to a single file to stream\&.
.RE
.SH "EXAMPLES"
.sp
.RS 4
.ie n \{\
\h'-04'\(bu\h'+03'\c
.\}
.el \{\
.sp -1
.IP \(bu 2.3
.\}
Download file to the current directory:
.sp
.if n \{\
.RS 4
.\}
.nf
$ megals /Root

/Root
/Root/README

$ megaget /Root/README
$ ls

README
.fi
.if n \{\
.RE
.\}
.RE
.SH "REMOTE FILESYSTEM"
.sp
Mega\&.nz filesystem is represented as a tree of nodes of various types\&. Nodes are identified by a 8 character node handles (eg\&. 7Fdi3ZjC)\&. Structure of the filesystem is not encrypted\&.
.sp
Megatools maps node tree structure to a traditional filesystem paths (eg\&. /Root/SomeFile\&.DAT)\&.
.sp
\fBNOTE\fR: By the nature of Mega\&.nz storage, several files in the directory can have the same name\&. To allow access to such files, the names of conflicting files are extended by appending dot and their node handle like this:
.sp
.if n \{\
.RS 4
.\}
.nf
/Root/conflictingfile
/Root/conflictingfile\&.7Fdi3ZjC
/Root/conflictingfile\&.mEU23aSD
.fi
.if n \{\
.RE
.\}
.sp
You need to be aware of several special folders:
.PP
/Root
.RS 4
Writable directory representing the root of the filesystem\&.
.RE
.PP
/Trash
.RS 4
Trash directory where Mega\&.nz web client moves deleted files\&. This directory is not used by megatools when removing files\&.
.RE
.PP
/Inbox
.RS 4
Not sure\&.
.RE
.PP
/Contacts
.RS 4
Directory containing subdirectories representing your contacts list\&. If you want to add contacts to the list, simply create subdirectory named after the contact you want to add\&.
.RE
.PP
/Contacts/<email>
.RS 4
Directories representing individual contacts in your contacts list\&. These directories contain folders that others shared with you\&. All shared files are read\-only, at the moment\&.
.RE
.SH "SEE ALSO"
.sp
\fBmegatools\fR(7), \fBmegarc\fR(5), \fBmegadf\fR(1), \fBmegadl\fR(1), \fBmegaget\fR(1), \fBmegals\fR(1), \fBmegamkdir\fR(1), \fBmegaput\fR(1), \fBmegareg\fR(1), \fBmegarm\fR(1), \fBmegacopy\fR(1)\&.
.SH "MEGATOOLS"
.sp
Part of the \fBmegatools\fR(7) suite\&.
.SH "BUGS"
.sp
Report bugs at https://github\&.com/megous/megatools or megous@megous\&.com\&.
.SH "AUTHOR"
.sp
Megatools was written by Ondrej Jirman <megous@megous\&.com>, 2013\-2016\&.
.sp
Official website is http://megatools\&.megous\&.com\&.
