.TH lirc-lsremotes "1" "Last change: Aug 2015" "lirc-lsremotes @version@" "User Commands"
.SH NAME
.P
\fBlirc-lsremotes\fR - parse lirc configuration files.
.SH SYNOPSIS
.P
\fBlirc-lsremotes\fR [\fIoptions\fR] <directory>
.P
\fBlirc-lsremotes\fR [\fIoptions\fR] <file>


.SH DESCRIPTION
lirc-lsremotes can parse lirc remote configuration files (i. e., lircd.conf)
and display a condensed index line, the complete data and/or diagnostics.
.P
When given a directory (first form) it expects this to contain a number of
vendor directories, each of which containing one or more configuration files.
.P
In the second form lirc-lsremotes displays remote configurations for a given
config file.

.SH OPTIONS
.TP 4
.B -d, --dump
Dump the complete configuration data for listed configurations.
.TP 4
.B  -s, --silent
Only print diagnostics.
.TP 4
.B -v --version
Print version info
.TP 4
.B -h, --help
Print help message.
.SH EXAMPLES
Print a status line and possible diagnostics for a file:
.IP "" 4
.nf
$ lirc-lsremotes  remotes/hitachi/RM-466E.lircd.conf
.br
lirc-lsremotes: Warning RM-466E: you should specify a valid gap value
.br
hitachi;RM-466E.lircd.conf;no_lircmd;no_photo;RM-466E;timing;no_raw
.fi
.P
List a status line for all remotes under remotes, saving diagnostics into
a file:
.IP "" 4
.nf
$ lirc-lsremotes  remotes > remotes.list 2>warnings.txt
.fi
.

.SH "SEE ALSO"
http://sourceforge.net/projects/lirc-remotes
