.TH LIRCD-SETUP "8" "Last change: Oct 2016" "lircd-setup @version@" "System Administration Utilities"
.SH NAME
lircd-setup - Run setup commands in lirc_options.conf
.SH SYNOPSIS
.B lircd-setup
<\fIconfig-file\fR>
.SH DESCRIPTION
.P
This program runs commands defined in the keys
.I code
and
.I code1
\&..
.I code10
in the
.I modinit
section of the config file.

It's used as a one-shot service invoked before
.BR lircd(8)
\&, running code
which needs root privileges.
.P
The config file defaults to @etcdir@/lirc/lirc_options.conf if not
given as command line argument.

.SH SEE ALSO
.BR lircd(8)
