language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

before_install:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get update -qq ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]] ; then sudo apt-get install -y libcurl4-gnutls-dev libmms-dev libglib2.0-dev zlib1g-dev pkg-config libxml2-utils ; fi
  - npm install -g jsonlint

before_script: git -C .. clone https://github.com/MediaArea/ZenLib.git
env:
  global:
    - secure: NP+/jWbhIDs0JH+FOfElZnywkm/d9K+WAkuDp8STeSpTbWqBIQhEWfixVPlFMZWMaXTpCIEDcZ85+COdUTitLfF/XuTE5tmUD7MnVrqPLDtOTQSbhrC1ag7uiII9U2Usz/q8GMbuU+ZE3/0K4zrm531kWaBj8Ot0yIJlw6yXPQM=
    - secure: dV7qxDJxBGnMryijofYbkZjAWSpXrD16ZfGZ16m8ZGt4QQIKq/uavagOVaJlvQopeD5soUk4gbdlPcrl+RnPLoOpFUK6/znu1rWGwzAO3zzNqoFKOuzSeG3c1518ZaURCVZbBB77zJcPYkaeftFK5fEe7Yz9i0SeS1dXG6C/Vss=
  matrix:
    -
    - CXXFLAGS="-DMEDIAINFO_ADVANCED_NO -DMEDIAINFO_ARCHIVE_NO -DMEDIAINFO_DEMUX_NO -DMEDIAINFO_DVDIF_ANALYZE_NO -DMEDIAINFO_EVENTS_NO -DMEDIAINFO_LIBCURL_NO -DMEDIAINFO_LIBMMS_NO -DMEDIAINFO_MD5_NO -DMEDIAINFO_MINIMAL_YES -DMEDIAINFO_MPEGTS_DUPLICATE_NO -DMEDIAINFO_N19_NO -DMEDIAINFO_OTHERTEXT_NO -DMEDIAINFO_TRACE_NO -DMEDIAINFO_READTHREAD_NO -DMEDIAINFO_EXPORT_NO -DMEDIAINFO_TEXT_YES" RUN_TESTS="no"
    - CXXFLAGS="-DMEDIAINFO_ADVANCED_NO -DMEDIAINFO_REFERENCES_NO -DMEDIAINFO_FILTER_NO -DMEDIAINFO_DUPLICATE_NO -DMEDIAINFO_MACROBLOCKS_NO -DMEDIAINFO_TRACE_NO -DMEDIAINFO_TRACE_FFV1CONTENT_NO -DMEDIAINFO_IBI_NO -DMEDIAINFO_DIRECTORY_NO -DMEDIAINFO_LIBCURL_NO -DMEDIAINFO_LIBMMS_NO -DMEDIAINFO_DVDIF_ANALYZE_NO -DMEDIAINFO_MPEGTS_DUPLICATE_NO -DMEDIAINFO_READTHREAD_NO -DMEDIAINFO_MD5_NO -DMEDIAINFO_SHA1_NO -DMEDIAINFO_SHA2_NO -DMEDIAINFO_EVENTS_NO -DMEDIAINFO_DEMUX_NO -DMEDIAINFO_AES_NO -DMEDIAINFO_FIXITY_NO -DMEDIAINFO_READER_NO -DMEDIAINFO_NEXTPACKET_NO" RUN_TESTS="no"
    - CXXFLAGS="-DMEDIAINFO_ADVANCED_NO -DMEDIAINFO_REFERENCES_NO -DMEDIAINFO_FILTER_NO -DMEDIAINFO_DUPLICATE_NO -DMEDIAINFO_MACROBLOCKS_NO -DMEDIAINFO_TRACE_NO -DMEDIAINFO_TRACE_FFV1CONTENT_NO -DMEDIAINFO_IBI_NO -DMEDIAINFO_DIRECTORY_NO -DMEDIAINFO_LIBCURL_NO -DMEDIAINFO_LIBMMS_NO -DMEDIAINFO_DVDIF_ANALYZE_NO -DMEDIAINFO_MPEGTS_DUPLICATE_NO -DMEDIAINFO_READTHREAD_NO -DMEDIAINFO_MD5_NO -DMEDIAINFO_SHA1_NO -DMEDIAINFO_SHA2_NO -DMEDIAINFO_EVENTS_NO -DMEDIAINFO_DEMUX_NO -DMEDIAINFO_AES_NO -DMEDIAINFO_FIXITY_NO -DMEDIAINFO_NEXTPACKET_NO -DMEDIAINFO_ALL_NO -DMEDIAINFO_MIXML_YES" RUN_TESTS="mixml"
script:
    - (cd ../ZenLib/Project/GNU/Library && ./autogen.sh && ./configure && make) &&
      cd Project/GNU/Library/ && ./autogen.sh && ./configure --with-libcurl && make &&
      make clone_regression_files && make check &&
      mkdir ../../CMake/Build && cd ../../CMake/Build && cmake -DBUILD_ZENLIB=1 .. && make
