# Build configuration for https://www.tea-ci.org
# Tea CI is a fork of Drone CI with Cygwin/Msys2 support
# Feel free to share Tea CI to more open source developers
# http://docs.tea-ci.org/usage/overview/
# Please add your project to https://github.com/TeaCI/tea-ci/wiki/Msys2-on-Wine#use-msys2-in-tea-ci

build:
  image: teaci/msys$$arch
  pull: true
  shell: mingw$$arch
  commands:
    - if [ $$arch = 32 ]; then target=i686; fi
    - if [ $$arch = 64 ]; then target=x86_64; fi
    - pacman -S --needed --noconfirm --noprogressbar mingw-w64-${target}-cmake mingw-w64-${target}-ffmpeg mingw-w64-${target}-SDL2 mingw-w64-${target}-openal mingw-w64-${target}-sfml mingw-w64-${target}-extra-cmake-modules mingw-w64-${target}-cairo mingw-w64-${target}-zlib mingw-w64-${target}-libpng nasm mingw-w64-${target}-wxWidgets mingw-w64-${target}-crt-git mingw-w64-${target}-headers-git zip
    - git submodule update --init --recursive
    - cmake -DENABLE_FFMPEG=ON -DENABLE_SDL=ON -G "MSYS Makefiles"
    - make
notify:
  irc:
    prefix: build
    nick: vbam-ci
    channel: #vba-m
    server:
      host: irc.freenode.net
port: 6667
matrix:
  arch:
    - 64
    - 32

#publish:
#  github_release:
#    api_key: 4cd466723ff104154a6a206814ddaa159131f2ec
#    files:
#      - vbam.exe
#      - visualboyadvance-m.exe
#    checksum:
#      - sha256