---
sudo: required

services:
    - xvfb

matrix:
    fast_finish: true
    include:
        - env: BUILD_ENV=ubuntu
          language: cpp
          os: linux
          dist: trusty
          before_script:
              - ./installdeps
          script:
              - mkdir build
              - cd build
              - cmake .. -DENABLE_SDL=ON -DENABLE_OPENAL=ON
              - make -j2
              - xvfb-run ./visualboyadvance-m --help
          cache:
              directories:
                  - "$HOME/.ccache"
        - env: BUILD_ENV=mingw-w64
          language: cpp
          os: linux
          dist: trusty
          before_script:
              - ./installdeps MinGW-w64-x86_64
          script:
              - mkdir build
              - cd build
              - /usr/lib/mxe/usr/bin/x86_64-w64-mingw32.static-cmake .. -DENABLE_SDL=ON -DENABLE_OPENAL=ON
              - make -j2
          cache:
              directories:
                  - "$HOME/.ccache"
        - env: BUILD_ENV=mingw-w32
          language: cpp
          os: linux
          dist: trusty
          before_script:
              - ./installdeps MinGW-w64-i686
          script:
              - mkdir build
              - cd build
              - /usr/lib/mxe/usr/bin/i686-w64-mingw32.static-cmake .. -DENABLE_SDL=ON -DENABLE_OPENAL=ON
              - make -j2
          cache:
              directories:
                  - "$HOME/.ccache"
        - env: BUILD_ENV=libretro
          language: cpp
          os: linux
          dist: trusty
          before_install:
              - sudo apt-get -qqy update
              - sudo apt-get -qqy install build-essential ccache
          script:
              - cd src/libretro
              - make -j2 CXX="ccache g++" CC="ccache gcc"
          cache:
              directories:
                  - "$HOME/.ccache"
        - env: BUILD_ENV=mac
          language: cpp
          os: osx
          osx_image: xcode10.2
          before_script:
              - ./installdeps
          script:
              - mkdir build
              - cd build
              - cmake .. -DENABLE_SDL=ON -DENABLE_OPENAL=ON -DENABLE_LINK=ON
              - make -j2
#              - ./visualboyadvance-m.app/Contents/MacOS/visualboyadvance-m --help
          cache:
              directories:
                  - "$HOME/.ccache"
                  - /usr/local

notifications:
    webhooks:
        urls:
            - https://webhooks.gitter.im/e/b273e1f74f164855d115
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: never     # options: [always|never|change] default: always
