language: cpp

sudo: required
dist: trusty

matrix:
  include:
    - os: linux
      compiler: gcc
    - os: osx
      compiler: clang

script: cd Project/GNU/Library/ && ./autogen.sh && ./configure && make && mkdir ../../CMake/Build && cd ../../CMake/Build && cmake .. && make
