[[protocols]]
name = "kii_pro"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x59 = "KEY_POWER"
0x19 = "KEY_MUTE"
0x42 = "KEY_RED"
0x40 = "KEY_GREEN"
0x00 = "KEY_YELLOW"
0x03 = "KEY_BLUE"
0x4a = "KEY_BACK"
0x48 = "KEY_FORWARD"
0x08 = "KEY_PREVIOUSSONG"
0x0b = "KEY_NEXTSONG"
0x46 = "KEY_PLAYPAUSE"
0x44 = "KEY_STOP"
0x1f = "KEY_FAVORITES"
0x04 = "KEY_PVR"
0x4d = "KEY_EPG"
0x02 = "KEY_INFO"
0x09 = "KEY_SUBTITLE"
0x01 = "KEY_AUDIO"
0x0d = "KEY_HOMEPAGE"
0x11 = "KEY_TV"
0x06 = "KEY_UP"
0x5a = "KEY_LEFT"
0x1a = "KEY_ENTER"
0x1b = "KEY_RIGHT"
0x16 = "KEY_DOWN"
0x45 = "KEY_MENU"
0x05 = "KEY_ESC"
0x13 = "KEY_VOLUMEUP"
0x17 = "KEY_VOLUMEDOWN"
0x58 = "KEY_APPSELECT"
0x12 = "KEY_VENDOR"
0x55 = "KEY_PAGEUP"
0x15 = "KEY_PAGEDOWN"
0x52 = "KEY_1"
0x50 = "KEY_2"
0x10 = "KEY_3"
0x56 = "KEY_4"
0x54 = "KEY_5"
0x14 = "KEY_6"
0x4e = "KEY_7"
0x4c = "KEY_8"
0x0c = "KEY_9"
0x18 = "KEY_WWW"
0x0f = "KEY_0"
0x51 = "KEY_BACKSPACE"
