[[protocols]]
name = "vega_s9x"
protocol = "nec"
variant = "nec"
[protocols.scancodes]
0x18 = "KEY_POWER"
0x17 = "KEY_MUTE"
0x46 = "KEY_UP"
0x47 = "KEY_LEFT"
0x55 = "KEY_OK"
0x15 = "KEY_RIGHT"
0x16 = "KEY_DOWN"
0x06 = "KEY_HOME"
0x42 = "KEY_PLAYPAUSE"
0x40 = "KEY_BACK"
0x14 = "KEY_VOLUMEDOWN"
0x04 = "KEY_MENU"
0x10 = "KEY_VOLUMEUP"
