name: dstat
version: 0.7.3
summary: Versatile resource statistic tool 
description: dstat is a versatile replacement for vmstat, iostat, and ifstat.
confinement: strict

apps:
  dstat:
    command: usr/bin/dstat
    plugs: [home, system-observe]
parts:
  dstat:
    plugin: make 
    source: https://github.com/dagwieers/dstat/archive/0.7.3.tar.gz 
    build-packages: [gcc, libc6-dev]
    stage-packages: [python2.7]

  python2-symlink:
    plugin: copy
    files: 
      python2: usr/bin/
    snap:
      - -usr/lib/gcc
      - -usr/lib/mime
      - -usr/lib/x86_64-linux-gnu
      - -lib/x86_64-linux-gnu
      - usr/bin/python2
      - usr/bin/python2.7
      - usr/bin/dstat
