#!/bin/sh

scripts/bttv.pl ../linux/drivers/media/pci/bt8xx/bttv.h  ../linux/drivers/media/pci/bt8xx/bttv-cards.c \
	| perl -ne 's/[ \t]+$//; print' > ../linux/Documentation/video4linux/CARDLIST.bttv

scripts/cx88.pl ../linux/drivers/media/pci/cx88/cx88.h ../linux/drivers/media/pci/cx88/cx88-cards.c \
	| perl -ne 's/[ \t]+$//; print' > ../linux/Documentation/video4linux/CARDLIST.cx88

scripts/em28xx.pl ../linux/drivers/media/usb/em28xx/em28xx-cards.c ../linux/drivers/usb/video/em28xx/em28xx.h \
	| perl -ne 's/[ \t]+$//; print' > ../linux/Documentation/video4linux/CARDLIST.em28xx

scripts/tuner.pl ../linux/include/media/tuner.h ../linux/drivers/media/tuners/tuner-types.c \
	| perl -ne 's/[ \t]+$//; print' > ../linux/Documentation/video4linux/CARDLIST.tuner

scripts/saa7134.pl ../linux/drivers/media/pci/saa7134/saa7134.h ../linux/drivers/media/pci/saa7134/saa7134-cards.c \
	| perl -ne 's/[ \t]+$//; print' > ../linux/Documentation/video4linux/CARDLIST.saa7134

scripts/usbvision.pl ../linux/drivers/media/usb/usbvision/usbvision-cards.h ../linux/drivers/media/usb/usbvision/usbvision-cards.c \
	| perl -ne 's/[ \t]+$//; print' > ../linux/Documentation/video4linux/CARDLIST.usbvision

scripts/cx23885.pl ../linux/drivers/media/pci/cx23885/cx23885.h ../linux/drivers/media/pci/cx23885/cx23885-cards.c \
	| perl -ne 's/[ \t]+$//; print' > ../linux/Documentation/video4linux/CARDLIST.cx23885

scripts/au0828.pl ../linux/drivers/media/usb/au0828/au0828-cards.h ../linux/drivers/media/usb/au0828/au0828-cards.c \
	| perl -ne 's/[ \t]+$//; print' > ../linux/Documentation/video4linux/CARDLIST.au0828

scripts/saa7164.pl ../linux/drivers/media/pci/saa7164/saa7164.h ../linux/drivers/media/pci/saa7164/saa7164-cards.c \
	| perl -ne 's/[ \t]+$//; print' > ../linux/Documentation/video4linux/CARDLIST.saa7164
