#
# Makefile for the amlogic video device interface device drivers.
#
asflags-y =-mfloat-abi=softfp -mfpu=neon

obj-m +=amlcm.o amlvideodri.o videobuf-res.o

amlvideodri-objs := amlvideo.o
amlcm-objs := vfutil.o
videobuf-res-obj := videobuf-res.o


