# From sound/pci/Makefile

snd-bt87x-objs := bt87x.o
obj-$(CONFIG_SND_BT87X) += snd-bt87x.o

KDIRA          := /lib/modules/$(KERNELRELEASE)/kernel


sound-install install-sound::
	@dir="sound/pci"; \
	files='snd-bt87x.ko'; \
	echo -e "\nInstalling $(KDIRA)/$$dir files:"; \
	install -d $(KDIRA)/$$dir; \
	for i in $$files;do if [ -e $$i ]; then echo -n "$$i "; \
	install -m 644 -c $$i $(KDIRA)/$$dir; fi; done; echo;
